///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.CrearCuentaEmpresa
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ActualizaDireccion recording.
    /// </summary>
    [TestModule("9a19f4b8-bf0d-4d70-9973-dbcf49d0c08b", ModuleType.Recording, 1)]
    public partial class ActualizaDireccion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static ActualizaDireccion instance = new ActualizaDireccion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ActualizaDireccion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ActualizaDireccion Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", "Trae Datos de la Dirección", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SURA.lbl_DireccionVerificada1'", repo.SURA.lbl_DireccionVerificada1Info, new ActionTimeout(5000), new RecordItemIndex(1));
            repo.SURA.lbl_DireccionVerificada1Info.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA_COF.Btn_ActualizarDireccion_COF' at Center.", repo.SURA_COF.Btn_ActualizarDireccion_COFInfo, new RecordItemIndex(2));
            repo.SURA_COF.Btn_ActualizarDireccion_COF.Click();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 30s to exist. Associated repository item: 'SURA_COF.lbl_ExisteCtaAnonimaConMismoDNI_COF1'", repo.SURA_COF.lbl_ExisteCtaAnonimaConMismoDNI_COF1Info, new ActionTimeout(30000), new RecordItemIndex(3));
                repo.SURA_COF.lbl_ExisteCtaAnonimaConMismoDNI_COF1Info.WaitForExists(30000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'SURA_COF.Btn_ActualizarDireccion_COF' at Center.", repo.SURA_COF.Btn_ActualizarDireccion_COFInfo, new RecordItemIndex(4));
                repo.SURA_COF.Btn_ActualizarDireccion_COF.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.txt_Cotizacion11'", repo.SURA.txt_Cotizacion11Info, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SURA.txt_Cotizacion11Info.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
