///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.CrearCuentaEmpresa
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscarCuentaCompania recording.
    /// </summary>
    [TestModule("b244f87c-c2dc-4b2c-95b8-8617f5a2dc30", ModuleType.Recording, 1)]
    public partial class BuscarCuentaCompania : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static BuscarCuentaCompania instance = new BuscarCuentaCompania();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscarCuentaCompania()
        {
            Name = "pruebauno";
            LastName = "cuenta";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscarCuentaCompania Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("597b2448-3081-4629-9a39-4eb67e488625")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("285060e8-8e35-4bb2-a974-20cbaa392819")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.Btn_Cuenta'", repo.ApplicationUnderTest.Btn_CuentaInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.Btn_CuentaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_Cuenta' at CenterRight.", repo.ApplicationUnderTest.Btn_CuentaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Btn_Cuenta.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_NuevaCuenta1' at 46;11.", repo.ApplicationUnderTest.Btn_NuevaCuenta1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Btn_NuevaCuenta1.Click("46;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_Nombre' at 78;15.", repo.ApplicationUnderTest.txt_NombreInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.txt_Nombre.Click("78;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Name' with focus on 'ApplicationUnderTest.txt_Nombre'.", repo.ApplicationUnderTest.txt_NombreInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.txt_Nombre.PressKeys(Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Name, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IngresarInformacionDeLaCuenta' at 285;15.", repo.ApplicationUnderTest.IngresarInformacionDeLaCuentaInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.IngresarInformacionDeLaCuenta.Click("285;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.txt_NombreEspera'", repo.ApplicationUnderTest.txt_NombreEsperaInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.ApplicationUnderTest.txt_NombreEsperaInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_Apellido' at 74;10.", repo.ApplicationUnderTest.txt_ApellidoInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.txt_Apellido.Click("74;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'ApplicationUnderTest.txt_Apellido'.", repo.ApplicationUnderTest.txt_ApellidoInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.txt_Apellido.EnsureVisible();
            Keyboard.Press(LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", LastName, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IngresarInformacionDeLaCuenta' at 285;15.", repo.ApplicationUnderTest.IngresarInformacionDeLaCuentaInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.IngresarInformacionDeLaCuenta.Click("285;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.txt_ApellidoEspera'", repo.ApplicationUnderTest.txt_ApellidoEsperaInfo, new ActionTimeout(30000), new RecordItemIndex(12));
            repo.ApplicationUnderTest.txt_ApellidoEsperaInfo.WaitForNotExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Bucar' at 34;12.", repo.ApplicationUnderTest.BucarInfo, new RecordItemIndex(13));
            //repo.ApplicationUnderTest.Bucar.Click("34;12");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_CrearCuentaNueva' at 93;10.", repo.ApplicationUnderTest.Btn_CrearCuentaNuevaInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.Btn_CrearCuentaNueva.Click("93;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Compania' at 45;12.", repo.ApplicationUnderTest.CompaniaInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.Compania.Click("45;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.bl_CrearCuenta' at 91;12.", repo.ApplicationUnderTest.bl_CrearCuentaInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.bl_CrearCuenta.Click("91;12");
            Delay.Milliseconds(0);
            
            // **** Validación a próxima ventana - Cargar Datos de la Cuenta ****
            Report.Log(ReportLevel.Info, "Section", "**** Validación a próxima ventana - Cargar Datos de la Cuenta ****", new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Crear cuenta') on item 'ApplicationUnderTest.bl_CrearCuenta'.", repo.ApplicationUnderTest.bl_CrearCuentaInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.ApplicationUnderTest.bl_CrearCuentaInfo, "InnerText", "Crear cuenta");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.bl_CrearCuenta'", repo.ApplicationUnderTest.bl_CrearCuentaInfo, new ActionTimeout(30000), new RecordItemIndex(19));
            //repo.ApplicationUnderTest.bl_CrearCuentaInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
