///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.CrearCuentaEmpresa
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CompletaDatosCuenta recording.
    /// </summary>
    [TestModule("9939a8db-a670-4cb0-9b27-b618cf723219", ModuleType.Recording, 1)]
    public partial class CompletaDatosCuenta : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static CompletaDatosCuenta instance = new CompletaDatosCuenta();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CompletaDatosCuenta()
        {
            IVA = "Exento";
            IBB = "Exento";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CompletaDatosCuenta Instance
        {
            get { return instance; }
        }

#region Variables

        string _IVA;

        /// <summary>
        /// Gets or sets the value of variable IVA.
        /// </summary>
        [TestVariable("331ffcff-0d67-4aee-96e4-3e3869ea6349")]
        public string IVA
        {
            get { return _IVA; }
            set { _IVA = value; }
        }

        string _IBB;

        /// <summary>
        /// Gets or sets the value of variable IBB.
        /// </summary>
        [TestVariable("dcf09a87-dc4f-4aae-8fa5-d3c7129b3c9e")]
        public string IBB
        {
            get { return _IBB; }
            set { _IBB = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$IVA' with focus on 'SURA.txt_IVA'.", repo.SURA.txt_IVAInfo, new RecordItemIndex(0));
            repo.SURA.txt_IVA.PressKeys(IVA);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.XTableLayout.CondicionFiscal' at Center.", repo.SURA.XTableLayout.CondicionFiscalInfo, new RecordItemIndex(1));
            repo.SURA.XTableLayout.CondicionFiscal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.txt_IVA_Espera'", repo.SURA.txt_IVA_EsperaInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.SURA.txt_IVA_EsperaInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.XTableLayout.FlechaSelectIBB' at Center.", repo.SURA.XTableLayout.FlechaSelectIBBInfo, new RecordItemIndex(3));
            repo.SURA.XTableLayout.FlechaSelectIBB.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$IBB' with focus on 'SURA.txt_IBB'.", repo.SURA.txt_IBBInfo, new RecordItemIndex(4));
            repo.SURA.txt_IBB.PressKeys(IBB);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.XTableLayout.CondicionFiscal' at Center.", repo.SURA.XTableLayout.CondicionFiscalInfo, new RecordItemIndex(5));
            repo.SURA.XTableLayout.CondicionFiscal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.txt_IBB_Espera'", repo.SURA.txt_IBB_EsperaInfo, new ActionTimeout(30000), new RecordItemIndex(6));
            repo.SURA.txt_IBB_EsperaInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.ClickFlechaBuscaGrupo2' at CenterRight.", repo.SURA.ClickFlechaBuscaGrupo2Info, new RecordItemIndex(7));
            repo.SURA.ClickFlechaBuscaGrupo2.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.BuscarGrupo' at Center.", repo.SURA.BuscarGrupoInfo, new RecordItemIndex(8));
            repo.SURA.BuscarGrupo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Validar_BuscarGrupos' at 112;14.", repo.SURA.Validar_BuscarGruposInfo, new RecordItemIndex(9));
            repo.SURA.Validar_BuscarGrupos.Click("112;14");
            Delay.Milliseconds(0);
            
            // **** Validación de Carga de Datos de la Cuenta exitoso ****
            Report.Log(ReportLevel.Info, "Section", "**** Validación de Carga de Datos de la Cuenta exitoso ****", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Buscar grupos') on item 'SURA.Validar_BuscarGrupos'.", repo.SURA.Validar_BuscarGruposInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.SURA.Validar_BuscarGruposInfo, "InnerText", "Buscar grupos");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
