///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.BuscarCuenta
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscarCuentaCreada recording.
    /// </summary>
    [TestModule("1f61798e-0d10-4bd6-801c-f4f4318c50fe", ModuleType.Recording, 1)]
    public partial class BuscarCuentaCreada : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static BuscarCuentaCreada instance = new BuscarCuentaCreada();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscarCuentaCreada()
        {
            NroCuenta = "9251672551";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscarCuentaCreada Instance
        {
            get { return instance; }
        }

#region Variables

        string _NroCuenta;

        /// <summary>
        /// Gets or sets the value of variable NroCuenta.
        /// </summary>
        [TestVariable("7c7753b9-8901-4547-b052-7ce3b858f67d")]
        public string NroCuenta
        {
            get { return _NroCuenta; }
            set { _NroCuenta = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.MenuSupBuscar' at CenterRight.", repo.SURA.MenuSupBuscarInfo, new RecordItemIndex(0));
            repo.SURA.MenuSupBuscar.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Cuentas' at 24;5.", repo.SURA.CuentasInfo, new RecordItemIndex(2));
            repo.SURA.Cuentas.Click("24;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SURA.txt_cuenta'.", repo.SURA.txt_cuentaInfo, new RecordItemIndex(3));
            repo.SURA.txt_cuenta.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroCuenta' with focus on 'SURA.txt_cuenta'.", repo.SURA.txt_cuentaInfo, new RecordItemIndex(4));
            repo.SURA.txt_cuenta.EnsureVisible();
            Keyboard.Press(NroCuenta);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.btn_Buscar' at Center.", repo.SURA.btn_BuscarInfo, new RecordItemIndex(5));
            repo.SURA.btn_Buscar.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.btn_Buscar' at Center.", repo.SURA.btn_BuscarInfo, new RecordItemIndex(6));
            repo.SURA.btn_Buscar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.ResultadoBusquedaCuenta'", repo.SURA.ResultadoBusquedaCuentaInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.SURA.ResultadoBusquedaCuentaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.lbl_ResultadosDeLaBusqueda' at Center.", repo.SURA.lbl_ResultadosDeLaBusquedaInfo, new RecordItemIndex(8));
            repo.SURA.lbl_ResultadosDeLaBusqueda.MoveTo();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
