///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PC.PreProd.CuentaPersona
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CrearCuenta recording.
    /// </summary>
    [TestModule("d6c7f0e8-5b2b-4a3b-89b5-fc583b10825c", ModuleType.Recording, 1)]
    public partial class CrearCuenta : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PC.PCRepository repository.
        /// </summary>
        public static global::PC.PCRepository repo = global::PC.PCRepository.Instance;

        static CrearCuenta instance = new CrearCuenta();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CrearCuenta()
        {
            txtDNI = "25433788";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CrearCuenta Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtDNI;

        /// <summary>
        /// Gets or sets the value of variable txtDNI.
        /// </summary>
        [TestVariable("a054af55-8274-4933-aed4-dcc59f27eebf")]
        public string txtDNI
        {
            get { return _txtDNI; }
            set { _txtDNI = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XBtnSplitXBtnSplitRightXBtnWrap' at 63;10.", repo.ApplicationUnderTest.XBtnSplitXBtnSplitRightXBtnWrapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.XBtnSplitXBtnSplitRightXBtnWrap.Click("63;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NuevaCuenta' at 45;8.", repo.ApplicationUnderTest.NuevaCuentaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.NuevaCuenta.Click("45;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe' at 32;14.", repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSeInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe.Click("32;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'prueba' with focus on 'ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe'.", repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSeInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe.PressKeys("prueba");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(4));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe1' at 19;10.", repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe1Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe1.Click("19;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'automati' with focus on 'ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe1'.", repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.NewAccountNewAccountScreenNewAccountSe1.EnsureVisible();
            Keyboard.Press("automati");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Bucar' at 22;9.", repo.ApplicationUnderTest.BucarInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Bucar.Click("22;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(8));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_crearCuentaNueva' at 121;9.", repo.ApplicationUnderTest.Btn_crearCuentaNuevaInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Btn_crearCuentaNueva.Click("121;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NorthPanel.Personal' at 49;9.", repo.ApplicationUnderTest.NorthPanel.PersonalInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.NorthPanel.Personal.Click("49;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.GregarDocumento' at 88;8.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.GregarDocumentoInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.GregarDocumento.Click("88;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.XTableLayout.XGridCellInner' at 59;16.", repo.ApplicationUnderTest.XTableLayout.XGridCellInnerInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.XTableLayout.XGridCellInner.MoveTo("59;16");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.XTableLayout.XGridCellInner' at 123;23.", repo.ApplicationUnderTest.XTableLayout.XGridCellInnerInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.XTableLayout.XGridCellInner.MoveTo("123;23");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XTableLayout.OfficialIDType' at 63;58.", repo.ApplicationUnderTest.XTableLayout.OfficialIDTypeInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.XTableLayout.OfficialIDType.Click("63;58");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner' at 299;165.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInnerInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner.Click("299;165");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '25433788' on item 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner'.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInnerInfo, new RecordItemIndex(16));
            //repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner.Element.SetAttributeValue("InnerText", "25433788");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '25433788' with focus on 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner'.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInnerInfo, new RecordItemIndex(17));
            //repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner.EnsureVisible();
            //Keyboard.Press("25433788");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner' at 62;11.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInnerInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XGridCellInner.Click("62;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '25433789' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("25433789");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XTableLayout.OfficialIDValue' at -18;42.", repo.ApplicationUnderTest.XTableLayout.OfficialIDValueInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.XTableLayout.OfficialIDValue.Click("-18;42");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XTableLayout.Nombre' at 37;10.", repo.ApplicationUnderTest.XTableLayout.NombreInfo, new RecordItemIndex(21));
            //repo.ApplicationUnderTest.XTableLayout.Nombre.Click("37;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(22));
            //Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XTableLayout.ValidarDocumento' at 67;5.", repo.ApplicationUnderTest.XTableLayout.ValidarDocumentoInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.XTableLayout.ValidarDocumento.Click("67;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Seleccionar' at 26;15.", repo.ApplicationUnderTest.SeleccionarInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.Seleccionar.Click("26;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(25));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.HttpsSsurgwsoadev4OpcOracleoutsourc' at 7;6.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.HttpsSsurgwsoadev4OpcOracleoutsourcInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.HttpsSsurgwsoadev4OpcOracleoutsourc.Click("7;6");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XTableLayout.HttpsIPreproducciongestionSegurossu' at 5;5.", repo.ApplicationUnderTest.XTableLayout.HttpsIPreproducciongestionSegurossuInfo, new RecordItemIndex(27));
            //repo.ApplicationUnderTest.XTableLayout.HttpsIPreproducciongestionSegurossu.Click("5;5");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NorthPanel.BuscarGrupo' at 0;13.", repo.ApplicationUnderTest.NorthPanel.BuscarGrupoInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.NorthPanel.BuscarGrupo.Click("0;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GroupSearchPopupGroupSearchPickerScreen' at 76;16.", repo.ApplicationUnderTest.GroupSearchPopupGroupSearchPickerScreenInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.GroupSearchPopupGroupSearchPickerScreen.Click("76;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2302' with focus on 'ApplicationUnderTest.GroupSearchPopupGroupSearchPickerScreen'.", repo.ApplicationUnderTest.GroupSearchPopupGroupSearchPickerScreenInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.GroupSearchPopupGroupSearchPickerScreen.PressKeys("2302");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Bucar1' at 26;11.", repo.ApplicationUnderTest.Bucar1Info, new RecordItemIndex(31));
            repo.ApplicationUnderTest.Bucar1.Click("26;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Seleccionar1' at 26;6.", repo.ApplicationUnderTest.Seleccionar1Info, new RecordItemIndex(32));
            repo.ApplicationUnderTest.Seleccionar1.Click("26;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XFormArrowTriggerXFormArrowTrigge' at 7;12.", repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XFormArrowTriggerXFormArrowTriggeInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.CreateAccountSuraCreateAccountScreenCr.XFormArrowTriggerXFormArrowTrigge.Click("7;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NorthPanel.LiTag2302MattioliLuisFederico' at 67;7.", repo.ApplicationUnderTest.NorthPanel.LiTag2302MattioliLuisFedericoInfo, new RecordItemIndex(34));
            repo.ApplicationUnderTest.NorthPanel.LiTag2302MattioliLuisFederico.Click("67;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(35));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SpanTagU' at 1;8.", repo.ApplicationUnderTest.SpanTagUInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.SpanTagU.Click("1;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ResumenDelArchivoDeCuenta' at 272;10.", repo.ApplicationUnderTest.ResumenDelArchivoDeCuentaInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.ResumenDelArchivoDeCuenta.Click("272;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Resumen del archivo de cuenta') on item 'ApplicationUnderTest.ResumenDelArchivoDeCuenta'.", repo.ApplicationUnderTest.ResumenDelArchivoDeCuentaInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ResumenDelArchivoDeCuentaInfo, "InnerText", "Resumen del archivo de cuenta");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
