///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PC.PreProd.login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("d6181331-3a3d-4449-b2e4-176ac9570b89", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PC.PCRepository repository.
        /// </summary>
        public static global::PC.PCRepository repo = global::PC.PCRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginLoginScreenLoginDVUsername' at 31;7.", repo.ApplicationUnderTest.LoginLoginScreenLoginDVUsernameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.LoginLoginScreenLoginDVUsername.Click("31;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lmattioli' with focus on 'ApplicationUnderTest.LoginLoginScreenLoginDVUsername'.", repo.ApplicationUnderTest.LoginLoginScreenLoginDVUsernameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.LoginLoginScreenLoginDVUsername.PressKeys("lmattioli");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginLoginScreenLoginDVPassword' at 31;7.", repo.ApplicationUnderTest.LoginLoginScreenLoginDVPasswordInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.LoginLoginScreenLoginDVPassword.Click("31;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'silverarrow' with focus on 'ApplicationUnderTest.LoginLoginScreenLoginDVPassword'.", repo.ApplicationUnderTest.LoginLoginScreenLoginDVPasswordInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.LoginLoginScreenLoginDVPassword.PressKeys("silverarrow");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LogIn' at 27;14.", repo.ApplicationUnderTest.LogInInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.LogIn.Click("27;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Mis solicitudes de póliza') on item 'ApplicationUnderTest.MisSolicitudesDePoliza'.", repo.ApplicationUnderTest.MisSolicitudesDePolizaInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.MisSolicitudesDePolizaInfo, "InnerText", "Mis solicitudes de póliza");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
