///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.CrearCuentaValidaDNI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargaDatosCuentaValidaDNI recording.
    /// </summary>
    [TestModule("6ad964e9-26ee-4db5-a6dc-03fcd1ae7d02", ModuleType.Recording, 1)]
    public partial class CargaDatosCuentaValidaDNI : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static CargaDatosCuentaValidaDNI instance = new CargaDatosCuentaValidaDNI();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargaDatosCuentaValidaDNI()
        {
            Documento = "24566780";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargaDatosCuentaValidaDNI Instance
        {
            get { return instance; }
        }

#region Variables

        string _Documento;

        /// <summary>
        /// Gets or sets the value of variable Documento.
        /// </summary>
        [TestVariable("2111a245-abab-4d7a-84db-2a33e00f6211")]
        public string Documento
        {
            get { return _Documento; }
            set { _Documento = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Btn_AGregarDocumento' at 56;12.", repo.SURA.Btn_AGregarDocumentoInfo, new RecordItemIndex(0));
            repo.SURA.Btn_AGregarDocumento.Click("56;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.txt_TipoDocumento' at 105;16.", repo.SURA.txt_TipoDocumentoInfo, new RecordItemIndex(1));
            repo.SURA.txt_TipoDocumento.Click("105;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.Copy_of_txt_TipoDocumento'", repo.SURA.Copy_of_txt_TipoDocumentoInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.SURA.Copy_of_txt_TipoDocumentoInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Select_Tipo_Doc' at 29;13.", repo.SURA.Select_Tipo_DocInfo, new RecordItemIndex(3));
            repo.SURA.Select_Tipo_Doc.Click("29;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.Copy_of_TipoDocumentoDNI'", repo.SURA.Copy_of_TipoDocumentoDNIInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.SURA.Copy_of_TipoDocumentoDNIInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Txt_NumeroDoc' at 67;15.", repo.SURA.Txt_NumeroDocInfo, new RecordItemIndex(5));
            repo.SURA.Txt_NumeroDoc.Click("67;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Documento' with focus on 'SURA.Txt_NumeroDoc'.", repo.SURA.Txt_NumeroDocInfo, new RecordItemIndex(6));
            repo.SURA.Txt_NumeroDoc.EnsureVisible();
            Keyboard.Press(Documento);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Documento, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.ValidarDocumento' at 97;12.", repo.SURA.ValidarDocumentoInfo, new RecordItemIndex(8));
            repo.SURA.ValidarDocumento.Click("97;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 40s to not exist. Associated repository item: 'SURA.Copy_of_ValidarDocumento'", repo.SURA.Copy_of_ValidarDocumentoInfo, new ActionTimeout(40000), new RecordItemIndex(9));
            repo.SURA.Copy_of_ValidarDocumentoInfo.WaitForNotExists(40000);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'SURA_COF.Seleccionar_COF' at 37;13.", repo.SURA_COF.Seleccionar_COFInfo, new RecordItemIndex(10));
                repo.SURA_COF.Seleccionar_COF.Click("37;13");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.ClickFlechaBuscaGrupo2' at CenterRight.", repo.SURA.ClickFlechaBuscaGrupo2Info, new RecordItemIndex(11));
            repo.SURA.ClickFlechaBuscaGrupo2.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.BuscarGrupo' at Center.", repo.SURA.BuscarGrupoInfo, new RecordItemIndex(12));
            repo.SURA.BuscarGrupo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Validar_BuscarGrupos' at 112;14.", repo.SURA.Validar_BuscarGruposInfo, new RecordItemIndex(13));
            repo.SURA.Validar_BuscarGrupos.Click("112;14");
            Delay.Milliseconds(0);
            
            // **** Validación de Carga de Datos de la Cuenta exitoso ****
            Report.Log(ReportLevel.Info, "Section", "**** Validación de Carga de Datos de la Cuenta exitoso ****", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Buscar grupos') on item 'SURA.Validar_BuscarGrupos'.", repo.SURA.Validar_BuscarGruposInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.SURA.Validar_BuscarGruposInfo, "InnerText", "Buscar grupos");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
