///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PCQA.CrearCuentaValidaDNI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the COF_ApplicationUnderTest element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("974942a0-d03d-4d55-b8bc-555f389500a9")]
    public partial class COF_ApplicationUnderTest : RepoGenBaseFolder
    {
        static COF_ApplicationUnderTest instance = new COF_ApplicationUnderTest();

        /// <summary>
        /// Gets the singleton class instance representing the COF_ApplicationUnderTest element repository.
        /// </summary>
        [RepositoryFolder("974942a0-d03d-4d55-b8bc-555f389500a9")]
        public static COF_ApplicationUnderTest Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public COF_ApplicationUnderTest() 
            : base("COF_ApplicationUnderTest", "/", null, 0, false, "974942a0-d03d-4d55-b8bc-555f389500a9", ".\\RepositoryImages\\COF_ApplicationUnderTest974942a0.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("974942a0-d03d-4d55-b8bc-555f389500a9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class COF_ApplicationUnderTestFolders
    {
    }
#pragma warning restore 0436
}
