///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3e665b01-86e8-4e71-9c8c-f1835f8b6333")]
    public partial class PCRepository : RepoGenBaseFolder
    {
        static PCRepository instance = new PCRepository();
        PCRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        PCRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the PCRepository element repository.
        /// </summary>
        [RepositoryFolder("3e665b01-86e8-4e71-9c8c-f1835f8b6333")]
        public static PCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PCRepository() 
            : base("PCRepository", "/", null, 0, false, "3e665b01-86e8-4e71-9c8c-f1835f8b6333", ".\\RepositoryImages\\PCRepository3e665b01.rximgres")
        {
            _applicationundertest = new PCRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new PCRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3e665b01-86e8-4e71-9c8c-f1835f8b6333")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("eb0176e0-0cae-4fc3-a130-f8f9ba895327")]
        public virtual PCRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("39e55bab-2071-4a95-b4f9-442d36077844")]
        public virtual PCRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PCRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("eb0176e0-0cae-4fc3-a130-f8f9ba895327")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            PCRepositoryFolders.XTableLayoutFolder _xtablelayout;
            PCRepositoryFolders.CreateAccountSuraCreateAccountScreenCrFolder _createaccountsuracreateaccountscreencr;
            PCRepositoryFolders.NorthPanelFolder _northpanel;
            RepoItemInfo _loginloginscreenlogindvpasswordInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _missolicitudesdepolizaInfo;
            RepoItemInfo _loginloginscreenlogindvusernameInfo;
            RepoItemInfo _xbtnsplitxbtnsplitrightxbtnwrapInfo;
            RepoItemInfo _nuevacuentaInfo;
            RepoItemInfo _newaccountnewaccountscreennewaccountseInfo;
            RepoItemInfo _newaccountnewaccountscreennewaccountse1Info;
            RepoItemInfo _bucarInfo;
            RepoItemInfo _btn_crearcuentanuevaInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _seleccionarInfo;
            RepoItemInfo _groupsearchpopupgroupsearchpickerscreenInfo;
            RepoItemInfo _bucar1Info;
            RepoItemInfo _seleccionar1Info;
            RepoItemInfo _spantaguInfo;
            RepoItemInfo _resumendelarchivodecuentaInfo;
            RepoItemInfo _crearcuentaInfo;
            RepoItemInfo _imagenInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='i-preproducciongestion.segurossura.com.ar']", parentFolder, 30000, null, false, "eb0176e0-0cae-4fc3-a130-f8f9ba895327", "")
            {
                _xtablelayout = new PCRepositoryFolders.XTableLayoutFolder(this);
                _createaccountsuracreateaccountscreencr = new PCRepositoryFolders.CreateAccountSuraCreateAccountScreenCrFolder(this);
                _northpanel = new PCRepositoryFolders.NorthPanelFolder(this);
                _loginloginscreenlogindvpasswordInfo = new RepoItemInfo(this, "LoginLoginScreenLoginDVPassword", ".//tbody[#'Login-tbody']/tr[3]/td/?/?/table/tbody/tr[2]/td/div/div//input[@name='Login:LoginScreen:LoginDV:password']", 30000, null, "7df403d9-e8a4-483c-98e4-5b38cbaf633e");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//tbody[#'Login-tbody']/tr[3]//table/tbody/tr[3]/td/div/div/?/?/table/?/?/tr/td/a//span[@innertext='Log In' or @innertext='Iniciar sesión']", 30000, null, "155e4322-09e0-46b9-9d27-28a5268c0522");
                _missolicitudesdepolizaInfo = new RepoItemInfo(this, "MisSolicitudesDePoliza", ".//tbody[#'DesktopSubmissions-tbody']/tr[1]/td/div//span[@innertext='Mis solicitudes de póliza']", 30000, null, "46d5e9c3-f018-4484-9c36-1b5332d3dba5");
                _loginloginscreenlogindvusernameInfo = new RepoItemInfo(this, "LoginLoginScreenLoginDVUsername", ".//tbody[#'Login-tbody']/tr[3]/td/?/?/table/tbody/tr[1]/td/div/div//input[@name='Login:LoginScreen:LoginDV:username']", 30000, null, "d0600a6d-0a32-4819-b404-0ebd173c9fdd");
                _xbtnsplitxbtnsplitrightxbtnwrapInfo = new RepoItemInfo(this, "XBtnSplitXBtnSplitRightXBtnWrap", ".//a[#'TabBar:AccountTab']/span", 30000, null, "d40481b5-c9e9-45fc-a336-c278be5f052a");
                _nuevacuentaInfo = new RepoItemInfo(this, "NuevaCuenta", "body/div[11]/div/div[2]/div/div[1]/?/?/span[@innertext='Nueva cuenta']", 30000, null, "1a957adb-768b-4a2f-bd97-6afcd0ebfcb4");
                _newaccountnewaccountscreennewaccountseInfo = new RepoItemInfo(this, "NewAccountNewAccountScreenNewAccountSe", ".//tbody[#'NewAccount-tbody']/tr[4]/td/?/?/table/tbody/tr[4]/td/div/div//input[@name='NewAccount:NewAccountScreen:NewAccountSearchDV:GlobalPersonNameInputSet:FirstName']", 30000, null, "a4de3e2c-8621-4001-ab3d-8673765257fa");
                _newaccountnewaccountscreennewaccountse1Info = new RepoItemInfo(this, "NewAccountNewAccountScreenNewAccountSe1", ".//tbody[#'NewAccount-tbody']/tr[4]/td/?/?/table/tbody/tr[5]/td/div/div//input[@name='NewAccount:NewAccountScreen:NewAccountSearchDV:GlobalPersonNameInputSet:LastName']", 30000, null, "350e2d47-556b-4811-942b-2ee2c71ab08e");
                _bucarInfo = new RepoItemInfo(this, "Bucar", ".//tbody[#'NewAccount-tbody']/tr[4]//table/tbody/tr[12]/td/div/div/?/?/table/?/?/tr/td[1]/a[@innertext='Bucar']", 30000, null, "64e91ac3-3e5b-4669-9ffc-658fc284adfe");
                _btn_crearcuentanuevaInfo = new RepoItemInfo(this, "Btn_crearCuentaNueva", ".//tbody[#'NewAccount-tbody']/tr[5]/td/div/table/tbody//span", 30000, null, "29732883-eb8c-479a-8694-950dfd13b13b");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", "body/div", 30000, null, "0c15d93f-08d3-45b1-b57e-f15206fdb409");
                _seleccionarInfo = new RepoItemInfo(this, "Seleccionar", ".//tbody[#'VerifiedAddressSelectionPopup-tbody']/tr[3]/td/div/div[3]/div[1]/div/table[1]/?/?/tr/td[1]/?/?/a[@innertext='Seleccionar']", 30000, null, "4d8cd9f1-a7cf-4474-a138-4f19730310a5");
                _groupsearchpopupgroupsearchpickerscreenInfo = new RepoItemInfo(this, "GroupSearchPopupGroupSearchPickerScreen", ".//tbody[#'GroupSearchPopup-tbody']/tr[3]/td/?/?/table/tbody/tr[3]/td/div/div//input[@name='GroupSearchPopup:GroupSearchPickerScreen:GroupSearchDV:ProducerCode']", 30000, null, "2e5825e8-81c6-4a18-a8c7-531d6e864e0c");
                _bucar1Info = new RepoItemInfo(this, "Bucar1", ".//tbody[#'GroupSearchPopup-tbody']/tr[3]//table/tbody/tr[5]/td/div/div/?/?/table/?/?/tr/td[1]/a[@innertext='Bucar']", 30000, null, "674ccd4b-55a8-4c20-b37f-4926deffc107");
                _seleccionar1Info = new RepoItemInfo(this, "Seleccionar1", ".//tbody[#'GroupSearchPopup-tbody']/tr[4]/td/div/div[4]/div[1]/div/table[2]/?/?/tr/td[1]/?/?/a[@innertext='Seleccionar']", 30000, null, "565c1f32-45fe-48a1-9d9c-538650fb3f73");
                _spantaguInfo = new RepoItemInfo(this, "SpanTagU", ".//tbody[#'CreateAccount-tbody']/tr[2]/td/div/div/div/a[1]//span[@innertext='Actalizar']/span[@innertext='u']", 30000, null, "96676929-e5be-44ed-a177-cc819ff5b9c0");
                _resumendelarchivodecuentaInfo = new RepoItemInfo(this, "ResumenDelArchivoDeCuenta", ".//tbody[#'AccountFile_Summary-tbody']/tr[1]/td/div//span[@innertext>'Resumen del archivo de cu']", 30000, null, "dbcefda5-e6c2-44b3-853d-8c970bf25aa7");
                _crearcuentaInfo = new RepoItemInfo(this, "CrearCuenta", ".//tbody[#'CreateAccount-tbody']/tr[1]/td/div//span[@innertext='Crear cuenta']", 30000, null, "320f8437-231e-4e22-b528-01c1f8703a91");
                _imagenInfo = new RepoItemInfo(this, "imagen", ".//img[@src='https://i-preproducciongestion.segurossura.com.ar/pc/resources/themes/theme-9/resources/images/app/drop_button.png']", 30000, null, "a10a8604-848b-4b09-b173-462356612a7e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eb0176e0-0cae-4fc3-a130-f8f9ba895327")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eb0176e0-0cae-4fc3-a130-f8f9ba895327")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginLoginScreenLoginDVPassword item.
            /// </summary>
            [RepositoryItem("7df403d9-e8a4-483c-98e4-5b38cbaf633e")]
            public virtual Ranorex.InputTag LoginLoginScreenLoginDVPassword
            {
                get
                {
                    return _loginloginscreenlogindvpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginLoginScreenLoginDVPassword item info.
            /// </summary>
            [RepositoryItemInfo("7df403d9-e8a4-483c-98e4-5b38cbaf633e")]
            public virtual RepoItemInfo LoginLoginScreenLoginDVPasswordInfo
            {
                get
                {
                    return _loginloginscreenlogindvpasswordInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("155e4322-09e0-46b9-9d27-28a5268c0522")]
            public virtual Ranorex.SpanTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("155e4322-09e0-46b9-9d27-28a5268c0522")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The MisSolicitudesDePoliza item.
            /// </summary>
            [RepositoryItem("46d5e9c3-f018-4484-9c36-1b5332d3dba5")]
            public virtual Ranorex.SpanTag MisSolicitudesDePoliza
            {
                get
                {
                    return _missolicitudesdepolizaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MisSolicitudesDePoliza item info.
            /// </summary>
            [RepositoryItemInfo("46d5e9c3-f018-4484-9c36-1b5332d3dba5")]
            public virtual RepoItemInfo MisSolicitudesDePolizaInfo
            {
                get
                {
                    return _missolicitudesdepolizaInfo;
                }
            }

            /// <summary>
            /// The LoginLoginScreenLoginDVUsername item.
            /// </summary>
            [RepositoryItem("d0600a6d-0a32-4819-b404-0ebd173c9fdd")]
            public virtual Ranorex.InputTag LoginLoginScreenLoginDVUsername
            {
                get
                {
                    return _loginloginscreenlogindvusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginLoginScreenLoginDVUsername item info.
            /// </summary>
            [RepositoryItemInfo("d0600a6d-0a32-4819-b404-0ebd173c9fdd")]
            public virtual RepoItemInfo LoginLoginScreenLoginDVUsernameInfo
            {
                get
                {
                    return _loginloginscreenlogindvusernameInfo;
                }
            }

            /// <summary>
            /// The XBtnSplitXBtnSplitRightXBtnWrap item.
            /// </summary>
            [RepositoryItem("d40481b5-c9e9-45fc-a336-c278be5f052a")]
            public virtual Ranorex.SpanTag XBtnSplitXBtnSplitRightXBtnWrap
            {
                get
                {
                    return _xbtnsplitxbtnsplitrightxbtnwrapInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The XBtnSplitXBtnSplitRightXBtnWrap item info.
            /// </summary>
            [RepositoryItemInfo("d40481b5-c9e9-45fc-a336-c278be5f052a")]
            public virtual RepoItemInfo XBtnSplitXBtnSplitRightXBtnWrapInfo
            {
                get
                {
                    return _xbtnsplitxbtnsplitrightxbtnwrapInfo;
                }
            }

            /// <summary>
            /// The NuevaCuenta item.
            /// </summary>
            [RepositoryItem("1a957adb-768b-4a2f-bd97-6afcd0ebfcb4")]
            public virtual Ranorex.SpanTag NuevaCuenta
            {
                get
                {
                    return _nuevacuentaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NuevaCuenta item info.
            /// </summary>
            [RepositoryItemInfo("1a957adb-768b-4a2f-bd97-6afcd0ebfcb4")]
            public virtual RepoItemInfo NuevaCuentaInfo
            {
                get
                {
                    return _nuevacuentaInfo;
                }
            }

            /// <summary>
            /// The NewAccountNewAccountScreenNewAccountSe item.
            /// </summary>
            [RepositoryItem("a4de3e2c-8621-4001-ab3d-8673765257fa")]
            public virtual Ranorex.InputTag NewAccountNewAccountScreenNewAccountSe
            {
                get
                {
                    return _newaccountnewaccountscreennewaccountseInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NewAccountNewAccountScreenNewAccountSe item info.
            /// </summary>
            [RepositoryItemInfo("a4de3e2c-8621-4001-ab3d-8673765257fa")]
            public virtual RepoItemInfo NewAccountNewAccountScreenNewAccountSeInfo
            {
                get
                {
                    return _newaccountnewaccountscreennewaccountseInfo;
                }
            }

            /// <summary>
            /// The NewAccountNewAccountScreenNewAccountSe1 item.
            /// </summary>
            [RepositoryItem("350e2d47-556b-4811-942b-2ee2c71ab08e")]
            public virtual Ranorex.InputTag NewAccountNewAccountScreenNewAccountSe1
            {
                get
                {
                    return _newaccountnewaccountscreennewaccountse1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NewAccountNewAccountScreenNewAccountSe1 item info.
            /// </summary>
            [RepositoryItemInfo("350e2d47-556b-4811-942b-2ee2c71ab08e")]
            public virtual RepoItemInfo NewAccountNewAccountScreenNewAccountSe1Info
            {
                get
                {
                    return _newaccountnewaccountscreennewaccountse1Info;
                }
            }

            /// <summary>
            /// The Bucar item.
            /// </summary>
            [RepositoryItem("64e91ac3-3e5b-4669-9ffc-658fc284adfe")]
            public virtual Ranorex.ATag Bucar
            {
                get
                {
                    return _bucarInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Bucar item info.
            /// </summary>
            [RepositoryItemInfo("64e91ac3-3e5b-4669-9ffc-658fc284adfe")]
            public virtual RepoItemInfo BucarInfo
            {
                get
                {
                    return _bucarInfo;
                }
            }

            /// <summary>
            /// The Btn_crearCuentaNueva item.
            /// </summary>
            [RepositoryItem("29732883-eb8c-479a-8694-950dfd13b13b")]
            public virtual Ranorex.SpanTag Btn_crearCuentaNueva
            {
                get
                {
                    return _btn_crearcuentanuevaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_crearCuentaNueva item info.
            /// </summary>
            [RepositoryItemInfo("29732883-eb8c-479a-8694-950dfd13b13b")]
            public virtual RepoItemInfo Btn_crearCuentaNuevaInfo
            {
                get
                {
                    return _btn_crearcuentanuevaInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("0c15d93f-08d3-45b1-b57e-f15206fdb409")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("0c15d93f-08d3-45b1-b57e-f15206fdb409")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The Seleccionar item.
            /// </summary>
            [RepositoryItem("4d8cd9f1-a7cf-4474-a138-4f19730310a5")]
            public virtual Ranorex.ATag Seleccionar
            {
                get
                {
                    return _seleccionarInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Seleccionar item info.
            /// </summary>
            [RepositoryItemInfo("4d8cd9f1-a7cf-4474-a138-4f19730310a5")]
            public virtual RepoItemInfo SeleccionarInfo
            {
                get
                {
                    return _seleccionarInfo;
                }
            }

            /// <summary>
            /// The GroupSearchPopupGroupSearchPickerScreen item.
            /// </summary>
            [RepositoryItem("2e5825e8-81c6-4a18-a8c7-531d6e864e0c")]
            public virtual Ranorex.InputTag GroupSearchPopupGroupSearchPickerScreen
            {
                get
                {
                    return _groupsearchpopupgroupsearchpickerscreenInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GroupSearchPopupGroupSearchPickerScreen item info.
            /// </summary>
            [RepositoryItemInfo("2e5825e8-81c6-4a18-a8c7-531d6e864e0c")]
            public virtual RepoItemInfo GroupSearchPopupGroupSearchPickerScreenInfo
            {
                get
                {
                    return _groupsearchpopupgroupsearchpickerscreenInfo;
                }
            }

            /// <summary>
            /// The Bucar1 item.
            /// </summary>
            [RepositoryItem("674ccd4b-55a8-4c20-b37f-4926deffc107")]
            public virtual Ranorex.ATag Bucar1
            {
                get
                {
                    return _bucar1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Bucar1 item info.
            /// </summary>
            [RepositoryItemInfo("674ccd4b-55a8-4c20-b37f-4926deffc107")]
            public virtual RepoItemInfo Bucar1Info
            {
                get
                {
                    return _bucar1Info;
                }
            }

            /// <summary>
            /// The Seleccionar1 item.
            /// </summary>
            [RepositoryItem("565c1f32-45fe-48a1-9d9c-538650fb3f73")]
            public virtual Ranorex.ATag Seleccionar1
            {
                get
                {
                    return _seleccionar1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Seleccionar1 item info.
            /// </summary>
            [RepositoryItemInfo("565c1f32-45fe-48a1-9d9c-538650fb3f73")]
            public virtual RepoItemInfo Seleccionar1Info
            {
                get
                {
                    return _seleccionar1Info;
                }
            }

            /// <summary>
            /// The SpanTagU item.
            /// </summary>
            [RepositoryItem("96676929-e5be-44ed-a177-cc819ff5b9c0")]
            public virtual Ranorex.SpanTag SpanTagU
            {
                get
                {
                    return _spantaguInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagU item info.
            /// </summary>
            [RepositoryItemInfo("96676929-e5be-44ed-a177-cc819ff5b9c0")]
            public virtual RepoItemInfo SpanTagUInfo
            {
                get
                {
                    return _spantaguInfo;
                }
            }

            /// <summary>
            /// The ResumenDelArchivoDeCuenta item.
            /// </summary>
            [RepositoryItem("dbcefda5-e6c2-44b3-853d-8c970bf25aa7")]
            public virtual Ranorex.SpanTag ResumenDelArchivoDeCuenta
            {
                get
                {
                    return _resumendelarchivodecuentaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ResumenDelArchivoDeCuenta item info.
            /// </summary>
            [RepositoryItemInfo("dbcefda5-e6c2-44b3-853d-8c970bf25aa7")]
            public virtual RepoItemInfo ResumenDelArchivoDeCuentaInfo
            {
                get
                {
                    return _resumendelarchivodecuentaInfo;
                }
            }

            /// <summary>
            /// The CrearCuenta item.
            /// </summary>
            [RepositoryItem("320f8437-231e-4e22-b528-01c1f8703a91")]
            public virtual Ranorex.SpanTag CrearCuenta
            {
                get
                {
                    return _crearcuentaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CrearCuenta item info.
            /// </summary>
            [RepositoryItemInfo("320f8437-231e-4e22-b528-01c1f8703a91")]
            public virtual RepoItemInfo CrearCuentaInfo
            {
                get
                {
                    return _crearcuentaInfo;
                }
            }

            /// <summary>
            /// The imagen item.
            /// </summary>
            [RepositoryItem("a10a8604-848b-4b09-b173-462356612a7e")]
            public virtual Ranorex.ImgTag imagen
            {
                get
                {
                    return _imagenInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The imagen item info.
            /// </summary>
            [RepositoryItemInfo("a10a8604-848b-4b09-b173-462356612a7e")]
            public virtual RepoItemInfo imagenInfo
            {
                get
                {
                    return _imagenInfo;
                }
            }

            /// <summary>
            /// The XTableLayout folder.
            /// </summary>
            [RepositoryFolder("17150edf-cf8d-48be-bd87-02fefb0ed618")]
            public virtual PCRepositoryFolders.XTableLayoutFolder XTableLayout
            {
                get { return _xtablelayout; }
            }

            /// <summary>
            /// The CreateAccountSuraCreateAccountScreenCr folder.
            /// </summary>
            [RepositoryFolder("db136f04-4f71-444f-98d2-f3126ebf80da")]
            public virtual PCRepositoryFolders.CreateAccountSuraCreateAccountScreenCrFolder CreateAccountSuraCreateAccountScreenCr
            {
                get { return _createaccountsuracreateaccountscreencr; }
            }

            /// <summary>
            /// The NorthPanel folder.
            /// </summary>
            [RepositoryFolder("3295ec1b-83ac-4346-8f0b-16ea0f9b4b44")]
            public virtual PCRepositoryFolders.NorthPanelFolder NorthPanel
            {
                get { return _northpanel; }
            }
        }

        /// <summary>
        /// The XTableLayoutFolder folder.
        /// </summary>
        [RepositoryFolder("17150edf-cf8d-48be-bd87-02fefb0ed618")]
        public partial class XTableLayoutFolder : RepoGenBaseFolder
        {
            RepoItemInfo _xgridcellinnerInfo;
            RepoItemInfo _officialidtypeInfo;
            RepoItemInfo _validardocumentoInfo;
            RepoItemInfo _nombreInfo;
            RepoItemInfo _officialidvalueInfo;
            RepoItemInfo _httpsipreproducciongestionsegurossuInfo;

            /// <summary>
            /// Creates a new XTableLayout  folder.
            /// </summary>
            public XTableLayoutFolder(RepoGenBaseFolder parentFolder) :
                    base("XTableLayout", ".//tbody[#'CreateAccount-tbody']/tr[4]//table//div/table/?/?/tr/td[1]/?/?/table", parentFolder, 30000, null, false, "17150edf-cf8d-48be-bd87-02fefb0ed618", "")
            {
                _xgridcellinnerInfo = new RepoItemInfo(this, "XGridCellInner", "tbody/tr[2]/td/div/div[3]/div[1]/div/table/tbody/tr/td[2]/div", 30000, null, "608e54cf-a790-4d28-bc40-26960345db6e");
                _officialidtypeInfo = new RepoItemInfo(this, "OfficialIDType", "tbody/tr[2]/td/div/div[3]/div[1]/?/?/table/?/?/tr/td[2]/div", 30000, null, "e7d84e7e-64ab-43f6-833f-bf6406a5968b");
                _validardocumentoInfo = new RepoItemInfo(this, "ValidarDocumento", "tbody/tr[3]/td/div/div/div/table/tbody/tr/td/a//span[@innertext='Validar Documento']", 30000, null, "bbf6732c-c653-41f7-9fff-8ce5e8efdd41");
                _nombreInfo = new RepoItemInfo(this, "Nombre", "tbody/tr[5]//label/span[@innertext='Nombre']", 30000, null, "0891448d-0d1c-4970-9c5d-889e7ac2b30a");
                _officialidvalueInfo = new RepoItemInfo(this, "OfficialIDValue", "tbody/tr[2]/td/div/div[3]/div[1]/div[3]/div/div/div/?/?/input[@name='OfficialIDValue']", 30000, null, "a040817d-12b4-4216-b441-71c98dd99282");
                _httpsipreproducciongestionsegurossuInfo = new RepoItemInfo(this, "HttpsIPreproducciongestionSegurossu", "tbody/tr[22]/td/div/div/div/div/div/div/div[3]/a[@href='javascript:void(0)']", 30000, null, "ade1c2f6-13ff-4ae2-9e84-e12825748224");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17150edf-cf8d-48be-bd87-02fefb0ed618")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17150edf-cf8d-48be-bd87-02fefb0ed618")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The XGridCellInner item.
            /// </summary>
            [RepositoryItem("608e54cf-a790-4d28-bc40-26960345db6e")]
            public virtual Ranorex.DivTag XGridCellInner
            {
                get
                {
                    return _xgridcellinnerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The XGridCellInner item info.
            /// </summary>
            [RepositoryItemInfo("608e54cf-a790-4d28-bc40-26960345db6e")]
            public virtual RepoItemInfo XGridCellInnerInfo
            {
                get
                {
                    return _xgridcellinnerInfo;
                }
            }

            /// <summary>
            /// The OfficialIDType item.
            /// </summary>
            [RepositoryItem("e7d84e7e-64ab-43f6-833f-bf6406a5968b")]
            public virtual Ranorex.DivTag OfficialIDType
            {
                get
                {
                    return _officialidtypeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The OfficialIDType item info.
            /// </summary>
            [RepositoryItemInfo("e7d84e7e-64ab-43f6-833f-bf6406a5968b")]
            public virtual RepoItemInfo OfficialIDTypeInfo
            {
                get
                {
                    return _officialidtypeInfo;
                }
            }

            /// <summary>
            /// The ValidarDocumento item.
            /// </summary>
            [RepositoryItem("bbf6732c-c653-41f7-9fff-8ce5e8efdd41")]
            public virtual Ranorex.SpanTag ValidarDocumento
            {
                get
                {
                    return _validardocumentoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ValidarDocumento item info.
            /// </summary>
            [RepositoryItemInfo("bbf6732c-c653-41f7-9fff-8ce5e8efdd41")]
            public virtual RepoItemInfo ValidarDocumentoInfo
            {
                get
                {
                    return _validardocumentoInfo;
                }
            }

            /// <summary>
            /// The Nombre item.
            /// </summary>
            [RepositoryItem("0891448d-0d1c-4970-9c5d-889e7ac2b30a")]
            public virtual Ranorex.SpanTag Nombre
            {
                get
                {
                    return _nombreInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Nombre item info.
            /// </summary>
            [RepositoryItemInfo("0891448d-0d1c-4970-9c5d-889e7ac2b30a")]
            public virtual RepoItemInfo NombreInfo
            {
                get
                {
                    return _nombreInfo;
                }
            }

            /// <summary>
            /// The OfficialIDValue item.
            /// </summary>
            [RepositoryItem("a040817d-12b4-4216-b441-71c98dd99282")]
            public virtual Ranorex.InputTag OfficialIDValue
            {
                get
                {
                    return _officialidvalueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The OfficialIDValue item info.
            /// </summary>
            [RepositoryItemInfo("a040817d-12b4-4216-b441-71c98dd99282")]
            public virtual RepoItemInfo OfficialIDValueInfo
            {
                get
                {
                    return _officialidvalueInfo;
                }
            }

            /// <summary>
            /// The HttpsIPreproducciongestionSegurossu item.
            /// </summary>
            [RepositoryItem("ade1c2f6-13ff-4ae2-9e84-e12825748224")]
            public virtual Ranorex.ATag HttpsIPreproducciongestionSegurossu
            {
                get
                {
                    return _httpsipreproducciongestionsegurossuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsIPreproducciongestionSegurossu item info.
            /// </summary>
            [RepositoryItemInfo("ade1c2f6-13ff-4ae2-9e84-e12825748224")]
            public virtual RepoItemInfo HttpsIPreproducciongestionSegurossuInfo
            {
                get
                {
                    return _httpsipreproducciongestionsegurossuInfo;
                }
            }
        }

        /// <summary>
        /// The CreateAccountSuraCreateAccountScreenCrFolder folder.
        /// </summary>
        [RepositoryFolder("db136f04-4f71-444f-98d2-f3126ebf80da")]
        public partial class CreateAccountSuraCreateAccountScreenCrFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpsssurgwsoadev4opcoracleoutsourcInfo;
            RepoItemInfo _copy_of_httpsssurgwsoadev4opcoracleoutsourcInfo;
            RepoItemInfo _xformarrowtriggerxformarrowtriggeInfo;
            RepoItemInfo _gregardocumentoInfo;
            RepoItemInfo _xgridcellinnerInfo;

            /// <summary>
            /// Creates a new CreateAccountSuraCreateAccountScreenCr  folder.
            /// </summary>
            public CreateAccountSuraCreateAccountScreenCrFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateAccountSuraCreateAccountScreenCr", ".//tbody[#'CreateAccount-tbody']/tr[4]//table", parentFolder, 30000, null, false, "db136f04-4f71-444f-98d2-f3126ebf80da", "")
            {
                _httpsssurgwsoadev4opcoracleoutsourcInfo = new RepoItemInfo(this, "HttpsSsurgwsoadev4OpcOracleoutsourc", ".//div/table/?/?/tr/td[2]/?/?/table/tbody/tr[22]/td/div/div/div/div/div/div/div[3]/a[@href='javascript:void(0)']/img[@src~'drop_button.png']", 30000, null, "ded0c93d-8046-483a-97c5-9ae2d2fab89a");
                _copy_of_httpsssurgwsoadev4opcoracleoutsourcInfo = new RepoItemInfo(this, "Copy_of_HttpsSsurgwsoadev4OpcOracleoutsourc", ".//div/table/?/?/tr/td[2]/?/?/table/tbody/tr[22]/td/div/div/div/div/div/div/div[3]/a[@href='javascript:void(0)']/img[@src~'drop_button.png']", 30000, null, "5ae41654-54a6-44d0-96d1-5100d315bdce");
                _xformarrowtriggerxformarrowtriggeInfo = new RepoItemInfo(this, "XFormArrowTriggerXFormArrowTrigge", ".//div/table/?/?/tr/td[2]/?/?/table/tbody/tr[23]/td/div/div/div/div[2]", 30000, null, "51a58d50-9631-4915-9526-298ed351fabe");
                _gregardocumentoInfo = new RepoItemInfo(this, "GregarDocumento", ".//td/?/?/table/tbody/tr/td[1]/?/?/table/tbody/tr[2]/td/div/div[1]/div/div/a[1]//span[@innertext='gregar Documento']", 30000, null, "8b42ad17-14ea-4325-849e-073b825588be");
                _xgridcellinnerInfo = new RepoItemInfo(this, "XGridCellInner", "tbody/tr//table/?/?/tr/td[1]/?/?/table/tbody/tr[2]/td/div/div[3]/div[1]/div[1]/table/?/?/tr/td[3]/div", 30000, null, "094e72cc-5e2c-4c1c-9855-3832022da663");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db136f04-4f71-444f-98d2-f3126ebf80da")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db136f04-4f71-444f-98d2-f3126ebf80da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsSsurgwsoadev4OpcOracleoutsourc item.
            /// </summary>
            [RepositoryItem("ded0c93d-8046-483a-97c5-9ae2d2fab89a")]
            public virtual Ranorex.ImgTag HttpsSsurgwsoadev4OpcOracleoutsourc
            {
                get
                {
                    return _httpsssurgwsoadev4opcoracleoutsourcInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsSsurgwsoadev4OpcOracleoutsourc item info.
            /// </summary>
            [RepositoryItemInfo("ded0c93d-8046-483a-97c5-9ae2d2fab89a")]
            public virtual RepoItemInfo HttpsSsurgwsoadev4OpcOracleoutsourcInfo
            {
                get
                {
                    return _httpsssurgwsoadev4opcoracleoutsourcInfo;
                }
            }

            /// <summary>
            /// The Copy_of_HttpsSsurgwsoadev4OpcOracleoutsourc item.
            /// </summary>
            [RepositoryItem("5ae41654-54a6-44d0-96d1-5100d315bdce")]
            public virtual Ranorex.ImgTag Copy_of_HttpsSsurgwsoadev4OpcOracleoutsourc
            {
                get
                {
                    return _copy_of_httpsssurgwsoadev4opcoracleoutsourcInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_HttpsSsurgwsoadev4OpcOracleoutsourc item info.
            /// </summary>
            [RepositoryItemInfo("5ae41654-54a6-44d0-96d1-5100d315bdce")]
            public virtual RepoItemInfo Copy_of_HttpsSsurgwsoadev4OpcOracleoutsourcInfo
            {
                get
                {
                    return _copy_of_httpsssurgwsoadev4opcoracleoutsourcInfo;
                }
            }

            /// <summary>
            /// The XFormArrowTriggerXFormArrowTrigge item.
            /// </summary>
            [RepositoryItem("51a58d50-9631-4915-9526-298ed351fabe")]
            public virtual Ranorex.DivTag XFormArrowTriggerXFormArrowTrigge
            {
                get
                {
                    return _xformarrowtriggerxformarrowtriggeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The XFormArrowTriggerXFormArrowTrigge item info.
            /// </summary>
            [RepositoryItemInfo("51a58d50-9631-4915-9526-298ed351fabe")]
            public virtual RepoItemInfo XFormArrowTriggerXFormArrowTriggeInfo
            {
                get
                {
                    return _xformarrowtriggerxformarrowtriggeInfo;
                }
            }

            /// <summary>
            /// The GregarDocumento item.
            /// </summary>
            [RepositoryItem("8b42ad17-14ea-4325-849e-073b825588be")]
            public virtual Ranorex.SpanTag GregarDocumento
            {
                get
                {
                    return _gregardocumentoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GregarDocumento item info.
            /// </summary>
            [RepositoryItemInfo("8b42ad17-14ea-4325-849e-073b825588be")]
            public virtual RepoItemInfo GregarDocumentoInfo
            {
                get
                {
                    return _gregardocumentoInfo;
                }
            }

            /// <summary>
            /// The XGridCellInner item.
            /// </summary>
            [RepositoryItem("094e72cc-5e2c-4c1c-9855-3832022da663")]
            public virtual Ranorex.DivTag XGridCellInner
            {
                get
                {
                    return _xgridcellinnerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The XGridCellInner item info.
            /// </summary>
            [RepositoryItemInfo("094e72cc-5e2c-4c1c-9855-3832022da663")]
            public virtual RepoItemInfo XGridCellInnerInfo
            {
                get
                {
                    return _xgridcellinnerInfo;
                }
            }
        }

        /// <summary>
        /// The NorthPanelFolder folder.
        /// </summary>
        [RepositoryFolder("3295ec1b-83ac-4346-8f0b-16ea0f9b4b44")]
        public partial class NorthPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _litag2302mattioliluisfedericoInfo;
            RepoItemInfo _buscargrupoInfo;
            RepoItemInfo _personalInfo;
            RepoItemInfo _xmenuitemlinkInfo;

            /// <summary>
            /// Creates a new NorthPanel  folder.
            /// </summary>
            public NorthPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("NorthPanel", "body/div[12]", parentFolder, 30000, null, false, "3295ec1b-83ac-4346-8f0b-16ea0f9b4b44", "")
            {
                _litag2302mattioliluisfedericoInfo = new RepoItemInfo(this, "LiTag2302MattioliLuisFederico", "?/?/ul/li[@innertext>'2302 Mattioli Luis Federi']", 30000, null, "b96813d3-24f4-4294-92af-e6489c7d84cd");
                _buscargrupoInfo = new RepoItemInfo(this, "BuscarGrupo", "div/div[2]//span[@innertext='Buscar grupo...']", 30000, null, "1a1b6758-e117-4405-8d97-55e8fee82e7c");
                _personalInfo = new RepoItemInfo(this, "Personal", "div/div[2]/div/div[2]/?/?/span[@innertext='Personal']", 30000, null, "01da156b-4ebf-46e5-b292-6c0480a4527d");
                _xmenuitemlinkInfo = new RepoItemInfo(this, "XMenuItemLink", "div/div[2]/div/div[2]/a", 30000, null, "86075013-f974-4ec9-828f-6f3f572c70f6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3295ec1b-83ac-4346-8f0b-16ea0f9b4b44")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3295ec1b-83ac-4346-8f0b-16ea0f9b4b44")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LiTag2302MattioliLuisFederico item.
            /// </summary>
            [RepositoryItem("b96813d3-24f4-4294-92af-e6489c7d84cd")]
            public virtual Ranorex.LiTag LiTag2302MattioliLuisFederico
            {
                get
                {
                    return _litag2302mattioliluisfedericoInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTag2302MattioliLuisFederico item info.
            /// </summary>
            [RepositoryItemInfo("b96813d3-24f4-4294-92af-e6489c7d84cd")]
            public virtual RepoItemInfo LiTag2302MattioliLuisFedericoInfo
            {
                get
                {
                    return _litag2302mattioliluisfedericoInfo;
                }
            }

            /// <summary>
            /// The BuscarGrupo item.
            /// </summary>
            [RepositoryItem("1a1b6758-e117-4405-8d97-55e8fee82e7c")]
            public virtual Ranorex.SpanTag BuscarGrupo
            {
                get
                {
                    return _buscargrupoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BuscarGrupo item info.
            /// </summary>
            [RepositoryItemInfo("1a1b6758-e117-4405-8d97-55e8fee82e7c")]
            public virtual RepoItemInfo BuscarGrupoInfo
            {
                get
                {
                    return _buscargrupoInfo;
                }
            }

            /// <summary>
            /// The Personal item.
            /// </summary>
            [RepositoryItem("01da156b-4ebf-46e5-b292-6c0480a4527d")]
            public virtual Ranorex.SpanTag Personal
            {
                get
                {
                    return _personalInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Personal item info.
            /// </summary>
            [RepositoryItemInfo("01da156b-4ebf-46e5-b292-6c0480a4527d")]
            public virtual RepoItemInfo PersonalInfo
            {
                get
                {
                    return _personalInfo;
                }
            }

            /// <summary>
            /// The XMenuItemLink item.
            /// </summary>
            [RepositoryItem("86075013-f974-4ec9-828f-6f3f572c70f6")]
            public virtual Ranorex.ATag XMenuItemLink
            {
                get
                {
                    return _xmenuitemlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The XMenuItemLink item info.
            /// </summary>
            [RepositoryItemInfo("86075013-f974-4ec9-828f-6f3f572c70f6")]
            public virtual RepoItemInfo XMenuItemLinkInfo
            {
                get
                {
                    return _xmenuitemlinkInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("39e55bab-2071-4a95-b4f9-442d36077844")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mostrarescritorioInfo;
            RepoItemInfo _pcranorexstudioadministratorInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "39e55bab-2071-4a95-b4f9-442d36077844", "")
            {
                _mostrarescritorioInfo = new RepoItemInfo(this, "MostrarEscritorio", "container[@controlid='303']/?/?/button[@accessiblename='Mostrar escritorio']", 30000, null, "aa0cd09d-fed3-406c-a002-aff9b0b3ceb8");
                _pcranorexstudioadministratorInfo = new RepoItemInfo(this, "PCRanorexStudioAdministrator", "?/?/container[@caption='Aplicaciones en ejecución']/?/?/toolbar[@accessiblename='Aplicaciones en ejecución']/button[@accessiblename>'PC - Ranorex Studio (Admi']", 30000, null, "4a48c31b-8d1f-4097-ae77-77e97e3a8677");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("39e55bab-2071-4a95-b4f9-442d36077844")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("39e55bab-2071-4a95-b4f9-442d36077844")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MostrarEscritorio item.
            /// </summary>
            [RepositoryItem("aa0cd09d-fed3-406c-a002-aff9b0b3ceb8")]
            public virtual Ranorex.Button MostrarEscritorio
            {
                get
                {
                    return _mostrarescritorioInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MostrarEscritorio item info.
            /// </summary>
            [RepositoryItemInfo("aa0cd09d-fed3-406c-a002-aff9b0b3ceb8")]
            public virtual RepoItemInfo MostrarEscritorioInfo
            {
                get
                {
                    return _mostrarescritorioInfo;
                }
            }

            /// <summary>
            /// The PCRanorexStudioAdministrator item.
            /// </summary>
            [RepositoryItem("4a48c31b-8d1f-4097-ae77-77e97e3a8677")]
            public virtual Ranorex.Button PCRanorexStudioAdministrator
            {
                get
                {
                    return _pcranorexstudioadministratorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PCRanorexStudioAdministrator item info.
            /// </summary>
            [RepositoryItemInfo("4a48c31b-8d1f-4097-ae77-77e97e3a8677")]
            public virtual RepoItemInfo PCRanorexStudioAdministratorInfo
            {
                get
                {
                    return _pcranorexstudioadministratorInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
