///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.Anular
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AnulaPoliza recording.
    /// </summary>
    [TestModule("7255da00-480d-461c-a448-6c665cc6ccdc", ModuleType.Recording, 1)]
    public partial class AnulaPoliza : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static AnulaPoliza instance = new AnulaPoliza();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AnulaPoliza()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AnulaPoliza Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Nuevo' at 40;13.", repo.ApplicationUnderTest.NuevoInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Nuevo.Click("40;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AnularPoliza' at 24;12.", repo.ApplicationUnderTest.AnularPolizaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.AnularPoliza.Click("24;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XFormArrowTriggerXFormArrowTrigge' at 4;11.", repo.ApplicationUnderTest.XFormArrowTriggerXFormArrowTriggeInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.XFormArrowTriggerXFormArrowTrigge.Click("4;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.Asegurado'", repo.ApplicationUnderTest.AseguradoInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.ApplicationUnderTest.AseguradoInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Asegurado' at 53;11.", repo.ApplicationUnderTest.AseguradoInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Asegurado.Click("53;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.XFormArrowTriggerXFormArrowTrigge1' at 8;13.", repo.ApplicationUnderTest.XFormArrowTriggerXFormArrowTrigge1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.XFormArrowTriggerXFormArrowTrigge1.Click("8;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 7s to exist. Associated repository item: 'ApplicationUnderTest.AnulacionPorDesistimiento'", repo.ApplicationUnderTest.AnulacionPorDesistimientoInfo, new ActionTimeout(7000), new RecordItemIndex(7));
            repo.ApplicationUnderTest.AnulacionPorDesistimientoInfo.WaitForExists(7000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AnulacionPorDesistimiento' at 114;8.", repo.ApplicationUnderTest.AnulacionPorDesistimientoInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.AnulacionPorDesistimiento.Click("114;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(9));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IniciarAnulacion' at 58;7.", repo.ApplicationUnderTest.IniciarAnulacionInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.IniciarAnulacion.Click("58;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AnularAhora' at 36;9.", repo.ApplicationUnderTest.AnularAhoraInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.AnularAhora.Click("36;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Aceptar' at 31;6.", repo.ApplicationUnderTest.AceptarInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Aceptar.Click("31;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Anulación Contratada') on item 'ApplicationUnderTest.AnulacionContratada'.", repo.ApplicationUnderTest.AnulacionContratadaInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AnulacionContratadaInfo, "InnerText", "Anulación Contratada");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
