///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscarCuentaAnswer recording.
    /// </summary>
    [TestModule("e50924db-a305-40b4-bb27-2360f7b99fc3", ModuleType.Recording, 1)]
    public partial class BuscarCuentaAnswer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PCQARepository repository.
        /// </summary>
        public static PCQARepository repo = PCQARepository.Instance;

        static BuscarCuentaAnswer instance = new BuscarCuentaAnswer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscarCuentaAnswer()
        {
            Name = "pruebauno";
            LastName = "cuenta";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscarCuentaAnswer Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("1994cee2-a736-4ccb-b231-5bb1e5d5b73b")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("8058427a-bc20-4513-92a2-bd194fba9ef8")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.Btn_Cuenta'", repo.SURA.Btn_CuentaInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.SURA.Btn_CuentaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Btn_Cuenta' at CenterRight.", repo.SURA.Btn_CuentaInfo, new RecordItemIndex(1));
            repo.SURA.Btn_Cuenta.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Btn_NuevaCuenta1' at 46;11.", repo.SURA.Btn_NuevaCuenta1Info, new RecordItemIndex(2));
            repo.SURA.Btn_NuevaCuenta1.Click("46;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.txt_Nombre' at 78;15.", repo.SURA.txt_NombreInfo, new RecordItemIndex(3));
            repo.SURA.txt_Nombre.Click("78;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Name' with focus on 'SURA.txt_Nombre'.", repo.SURA.txt_NombreInfo, new RecordItemIndex(4));
            repo.SURA.txt_Nombre.PressKeys(Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Name, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.IngresarInformacionDeLaCuenta' at 285;15.", repo.SURA.IngresarInformacionDeLaCuentaInfo, new RecordItemIndex(6));
            repo.SURA.IngresarInformacionDeLaCuenta.Click("285;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.txt_NombreEspera'", repo.SURA.txt_NombreEsperaInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.SURA.txt_NombreEsperaInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.txt_Apellido' at 74;10.", repo.SURA.txt_ApellidoInfo, new RecordItemIndex(8));
            repo.SURA.txt_Apellido.Click("74;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'SURA.txt_Apellido'.", repo.SURA.txt_ApellidoInfo, new RecordItemIndex(9));
            repo.SURA.txt_Apellido.EnsureVisible();
            Keyboard.Press(LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", LastName, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.IngresarInformacionDeLaCuenta' at 285;15.", repo.SURA.IngresarInformacionDeLaCuentaInfo, new RecordItemIndex(11));
            repo.SURA.IngresarInformacionDeLaCuenta.Click("285;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.txt_ApellidoEspera'", repo.SURA.txt_ApellidoEsperaInfo, new ActionTimeout(30000), new RecordItemIndex(12));
            repo.SURA.txt_ApellidoEsperaInfo.WaitForNotExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Bucar' at 34;12.", repo.SURA.BucarInfo, new RecordItemIndex(13));
            //repo.SURA.Bucar.Click("34;12");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Btn_CrearCuentaNueva' at 93;10.", repo.SURA.Btn_CrearCuentaNuevaInfo, new RecordItemIndex(14));
            repo.SURA.Btn_CrearCuentaNueva.Click("93;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Personal' at 45;12.", repo.SURA.PersonalInfo, new RecordItemIndex(15));
            repo.SURA.Personal.Click("45;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.bl_CrearCuenta' at 91;12.", repo.SURA.bl_CrearCuentaInfo, new RecordItemIndex(16));
            repo.SURA.bl_CrearCuenta.Click("91;12");
            Delay.Milliseconds(0);
            
            // **** Validación a próxima ventana - Cargar Datos de la Cuenta ****
            Report.Log(ReportLevel.Info, "Section", "**** Validación a próxima ventana - Cargar Datos de la Cuenta ****", new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Crear cuenta') on item 'SURA.bl_CrearCuenta'.", repo.SURA.bl_CrearCuentaInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.SURA.bl_CrearCuentaInfo, "InnerText", "Crear cuenta");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.bl_CrearCuenta'", repo.SURA.bl_CrearCuentaInfo, new ActionTimeout(30000), new RecordItemIndex(19));
            //repo.SURA.bl_CrearCuentaInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
