///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuEscritorioCuentaAnonima recording.
    /// </summary>
    [TestModule("d7396c5d-ccc1-4102-986a-8305de934e20", ModuleType.Recording, 1)]
    public partial class MenuEscritorioCuentaAnonima : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PCQARepository repository.
        /// </summary>
        public static PCQARepository repo = PCQARepository.Instance;

        static MenuEscritorioCuentaAnonima instance = new MenuEscritorioCuentaAnonima();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuEscritorioCuentaAnonima()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuEscritorioCuentaAnonima Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MenuNuevo' at 44;10.", repo.ApplicationUnderTest.MenuNuevoInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.MenuNuevo.Click("44;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GBannerXBoxItemXBoxLayoutCtXCo.SubMenuNuevaSolicitudAnonima' at 99;10.", repo.ApplicationUnderTest.GBannerXBoxItemXBoxLayoutCtXCo.SubMenuNuevaSolicitudAnonimaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.GBannerXBoxItemXBoxLayoutCtXCo.SubMenuNuevaSolicitudAnonima.Click("99;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubMenuPersona' at 22;12.", repo.ApplicationUnderTest.SubMenuPersonaInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SubMenuPersona.Click("22;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
