///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PCQA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PCQARepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2ca9e9c2-7d61-47da-a3e1-f1acb74838d1")]
    public partial class PCQARepository : RepoGenBaseFolder
    {
        static PCQARepository instance = new PCQARepository();
        PCQARepositoryFolders.SURAAppFolder _sura;

        /// <summary>
        /// Gets the singleton class instance representing the PCQARepository element repository.
        /// </summary>
        [RepositoryFolder("2ca9e9c2-7d61-47da-a3e1-f1acb74838d1")]
        public static PCQARepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PCQARepository() 
            : base("PCQARepository", "/", null, 0, false, "2ca9e9c2-7d61-47da-a3e1-f1acb74838d1", ".\\RepositoryImages\\PCQARepository2ca9e9c2.rximgres")
        {
            _sura = new PCQARepositoryFolders.SURAAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2ca9e9c2-7d61-47da-a3e1-f1acb74838d1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SURA folder.
        /// </summary>
        [RepositoryFolder("920b5cdc-6f8f-4038-b076-7e07ef5ce35b")]
        public virtual PCQARepositoryFolders.SURAAppFolder SURA
        {
            get { return _sura; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PCQARepositoryFolders
    {
        /// <summary>
        /// The SURAAppFolder folder.
        /// </summary>
        [RepositoryFolder("920b5cdc-6f8f-4038-b076-7e07ef5ce35b")]
        public partial class SURAAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_userInfo;
            RepoItemInfo _copy_of_txt_userInfo;
            RepoItemInfo _txt_passwordInfo;
            RepoItemInfo _btn_loginInfo;
            RepoItemInfo _validate_misactividadesInfo;
            RepoItemInfo _btn_cuentaInfo;
            RepoItemInfo _txt_nombreInfo;

            /// <summary>
            /// Creates a new SURA  folder.
            /// </summary>
            public SURAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SURA", "", parentFolder, 30000, null, false, "920b5cdc-6f8f-4038-b076-7e07ef5ce35b", "")
            {
                _txt_userInfo = new RepoItemInfo(this, "txt_User", "/dom[@domain~$Ambiente]//tbody[#'Login-tbody']/tr[3]/td/?/?/table/tbody/tr[1]/td/div/div//input[@name='Login:LoginScreen:LoginDV:username']", "", 30000, null, "991af7f4-171f-446b-a05f-aee8f85138b9");
                _copy_of_txt_userInfo = new RepoItemInfo(this, "Copy_of_txt_User", "/dom[@domain~$Ambiente]//tbody[#'Login-tbody']/tr[3]/td/?/?/table/tbody/tr[1]/td/div/div//input[@name='Login:LoginScreen:LoginDV:username']", "", 30000, null, "7edd13d0-db27-4895-8ca3-d07174bb176f");
                _txt_passwordInfo = new RepoItemInfo(this, "txt_password", "/dom[@domain~$Ambiente]//tbody[#'Login-tbody']/tr[3]/td/?/?/table/tbody/tr[2]/td/div/div//input[@name='Login:LoginScreen:LoginDV:password']", "", 30000, null, "4c7d9293-a61f-4c71-b246-a5e9c13d9f05");
                _btn_loginInfo = new RepoItemInfo(this, "Btn_LogIn", "/dom[@domain~$Ambiente]//tbody[#'Login-tbody']/tr[3]//table/tbody/tr[3]/td/div/div/?/?/table/?/?/tr/td/a//span[@innertext~'Log In' or @innertext~'Iniciar sesión']", "", 30000, null, "75064773-8d72-475e-b70b-9524910eb098");
                _validate_misactividadesInfo = new RepoItemInfo(this, "Validate_MisActividades", "/dom[@domain~$Ambiente]//tbody[#'DesktopSubmissions-tbody']/tr[1]/td/div//span[@innertext='Mis actividades']", "", 30000, null, "e4b7c230-301f-4d2c-b47f-229790ca18ae");
                _btn_cuentaInfo = new RepoItemInfo(this, "Btn_Cuenta", "/dom[@domain~$Ambiente]//a[#'TabBar:AccountTab']/span[@id='TabBar:AccountTab-btnWrap' and @visible='true']", "", 30000, null, "0785533c-0b7a-4de6-8ccb-827f4f2ed1a8");
                _txt_nombreInfo = new RepoItemInfo(this, "txt_Nombre", "", "", 30000, null, "0d206d0d-fd2d-4e3f-b6d9-780958a8018f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("920b5cdc-6f8f-4038-b076-7e07ef5ce35b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("920b5cdc-6f8f-4038-b076-7e07ef5ce35b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_User item.
            /// </summary>
            [RepositoryItem("991af7f4-171f-446b-a05f-aee8f85138b9")]
            public virtual Ranorex.InputTag txt_User
            {
                get
                {
                    return _txt_userInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_User item info.
            /// </summary>
            [RepositoryItemInfo("991af7f4-171f-446b-a05f-aee8f85138b9")]
            public virtual RepoItemInfo txt_UserInfo
            {
                get
                {
                    return _txt_userInfo;
                }
            }

            /// <summary>
            /// The Copy_of_txt_User item.
            /// </summary>
            [RepositoryItem("7edd13d0-db27-4895-8ca3-d07174bb176f")]
            public virtual Ranorex.InputTag Copy_of_txt_User
            {
                get
                {
                    return _copy_of_txt_userInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_txt_User item info.
            /// </summary>
            [RepositoryItemInfo("7edd13d0-db27-4895-8ca3-d07174bb176f")]
            public virtual RepoItemInfo Copy_of_txt_UserInfo
            {
                get
                {
                    return _copy_of_txt_userInfo;
                }
            }

            /// <summary>
            /// The txt_password item.
            /// </summary>
            [RepositoryItem("4c7d9293-a61f-4c71-b246-a5e9c13d9f05")]
            public virtual Ranorex.InputTag txt_password
            {
                get
                {
                    return _txt_passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_password item info.
            /// </summary>
            [RepositoryItemInfo("4c7d9293-a61f-4c71-b246-a5e9c13d9f05")]
            public virtual RepoItemInfo txt_passwordInfo
            {
                get
                {
                    return _txt_passwordInfo;
                }
            }

            /// <summary>
            /// The Btn_LogIn item.
            /// </summary>
            [RepositoryItem("75064773-8d72-475e-b70b-9524910eb098")]
            public virtual Ranorex.SpanTag Btn_LogIn
            {
                get
                {
                    return _btn_loginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_LogIn item info.
            /// </summary>
            [RepositoryItemInfo("75064773-8d72-475e-b70b-9524910eb098")]
            public virtual RepoItemInfo Btn_LogInInfo
            {
                get
                {
                    return _btn_loginInfo;
                }
            }

            /// <summary>
            /// The Validate_MisActividades item.
            /// </summary>
            [RepositoryItem("e4b7c230-301f-4d2c-b47f-229790ca18ae")]
            public virtual Ranorex.SpanTag Validate_MisActividades
            {
                get
                {
                    return _validate_misactividadesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Validate_MisActividades item info.
            /// </summary>
            [RepositoryItemInfo("e4b7c230-301f-4d2c-b47f-229790ca18ae")]
            public virtual RepoItemInfo Validate_MisActividadesInfo
            {
                get
                {
                    return _validate_misactividadesInfo;
                }
            }

            /// <summary>
            /// The Btn_Cuenta item.
            /// </summary>
            [RepositoryItem("0785533c-0b7a-4de6-8ccb-827f4f2ed1a8")]
            public virtual Ranorex.SpanTag Btn_Cuenta
            {
                get
                {
                    return _btn_cuentaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_Cuenta item info.
            /// </summary>
            [RepositoryItemInfo("0785533c-0b7a-4de6-8ccb-827f4f2ed1a8")]
            public virtual RepoItemInfo Btn_CuentaInfo
            {
                get
                {
                    return _btn_cuentaInfo;
                }
            }

            /// <summary>
            /// The txt_Nombre item.
            /// </summary>
            [RepositoryItem("0d206d0d-fd2d-4e3f-b6d9-780958a8018f")]
            public virtual Ranorex.InputTag txt_Nombre
            {
                get
                {
                    return _txt_nombreInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Nombre item info.
            /// </summary>
            [RepositoryItemInfo("0d206d0d-fd2d-4e3f-b6d9-780958a8018f")]
            public virtual RepoItemInfo txt_NombreInfo
            {
                get
                {
                    return _txt_nombreInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
