///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PCQA.Rehabilitar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Rehabilitar recording.
    /// </summary>
    [TestModule("40d80169-c6e6-47fe-a50b-2dcb305f9f8d", ModuleType.Recording, 1)]
    public partial class Rehabilitar : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PCQA.PCQARepository repository.
        /// </summary>
        public static global::PCQA.PCQARepository repo = global::PCQA.PCQARepository.Instance;

        static Rehabilitar instance = new Rehabilitar();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Rehabilitar()
        {
            NumeroTransaccion = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Rehabilitar Instance
        {
            get { return instance; }
        }

#region Variables

        string _NumeroTransaccion;

        /// <summary>
        /// Gets or sets the value of variable NumeroTransaccion.
        /// </summary>
        [TestVariable("92c2fee3-3c54-4390-a10a-cba580aebc6b")]
        public string NumeroTransaccion
        {
            get { return _NumeroTransaccion; }
            set { _NumeroTransaccion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("6220ee55-3dcc-4717-9260-d89ec7bc2052")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.bttn_Nuevo' at Center.", repo.SURA.Anulacion_Rehabilitacion.bttn_NuevoInfo, new RecordItemIndex(0));
            repo.SURA.Anulacion_Rehabilitacion.bttn_Nuevo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.bttn_RehabilitarPoliza' at Center.", repo.SURA.Anulacion_Rehabilitacion.bttn_RehabilitarPolizaInfo, new RecordItemIndex(1));
            repo.SURA.Anulacion_Rehabilitacion.bttn_RehabilitarPoliza.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.txt_IniciarLaRehabilitacion'", repo.SURA.Anulacion_Rehabilitacion.txt_IniciarLaRehabilitacionInfo, new ActionTimeout(20000), new RecordItemIndex(2));
            repo.SURA.Anulacion_Rehabilitacion.txt_IniciarLaRehabilitacionInfo.WaitForExists(20000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.txtbox_Motivo' at 9;4.", repo.SURA.Anulacion_Rehabilitacion.txtbox_MotivoInfo, new RecordItemIndex(3));
            repo.SURA.Anulacion_Rehabilitacion.txtbox_Motivo.Click("9;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'otro{Return}' with focus on 'SURA.Anulacion_Rehabilitacion.txtbox_Motivo'.", repo.SURA.Anulacion_Rehabilitacion.txtbox_MotivoInfo, new RecordItemIndex(4));
            repo.SURA.Anulacion_Rehabilitacion.txtbox_Motivo.PressKeys("otro{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.lbl_GrupoDeAfinidad' at 563;19.", repo.SURA.Anulacion_Rehabilitacion.lbl_GrupoDeAfinidadInfo, new RecordItemIndex(5));
            repo.SURA.Anulacion_Rehabilitacion.lbl_GrupoDeAfinidad.Click("563;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.bttn_Recotizar' at Center.", repo.SURA.Anulacion_Rehabilitacion.bttn_RecotizarInfo, new RecordItemIndex(6));
            repo.SURA.Anulacion_Rehabilitacion.bttn_Recotizar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.txt_Cotizacion'", repo.SURA.Anulacion_Rehabilitacion.txt_CotizacionInfo, new ActionTimeout(20000), new RecordItemIndex(7));
            repo.SURA.Anulacion_Rehabilitacion.txt_CotizacionInfo.WaitForExists(20000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.bttn_Rehabilitar' at Center.", repo.SURA.Anulacion_Rehabilitacion.bttn_RehabilitarInfo, new RecordItemIndex(9));
            repo.SURA.Anulacion_Rehabilitacion.bttn_Rehabilitar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.bttn_Aceptar' at Center.", repo.SURA.bttn_AceptarInfo, new RecordItemIndex(10));
            repo.SURA.bttn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Rehabilitación Contratada') on item 'SURA.Anulacion_Rehabilitacion.txt_RehabilitacionContratada'.", repo.SURA.Anulacion_Rehabilitacion.txt_RehabilitacionContratadaInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.SURA.Anulacion_Rehabilitacion.txt_RehabilitacionContratadaInfo, "InnerText", "Rehabilitación Contratada");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.Anulacion_Rehabilitacion.txt_NroRehabilitacion' and assigning the part of its value captured by '[0-9]{10}' to variable 'NumeroTransaccion'.", repo.SURA.Anulacion_Rehabilitacion.txt_NroRehabilitacionInfo, new RecordItemIndex(12));
            NumeroTransaccion = repo.SURA.Anulacion_Rehabilitacion.txt_NroRehabilitacion.Element.GetAttributeValueText("InnerText", new Regex("[0-9]{10}"));
            Delay.Milliseconds(0);
            
            // El número de transacción es
            Report.Log(ReportLevel.Info, "Section", "El número de transacción es", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "User", NumeroTransaccion, new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
